["Используемые домены"]

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TAGNTYPE"
    "Наименование (RU)" = "Тип контрагента"
    "Тип данных" = "Число"
    "Подтип данных" = "Простое число"
    "Точность данных" = 1.0
    "Дробность данных" = 0.0
    "Значение по умолчанию" = 0.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = true

        ["Используемые домены"."Домен"."Перечисляемые значения"]

            [["Используемые домены"."Домен"."Перечисляемые значения"."Перечисляемое значение"]]
            "Позиция" = "1"
            "Значение" = 0.0
            "Наименование (RU)" = "Юридическое лицо"

            [["Используемые домены"."Домен"."Перечисляемые значения"."Перечисляемое значение"]]
            "Позиция" = "2"
            "Значение" = 1.0
            "Наименование (RU)" = "Физическое лицо"

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TBOOLEAN"
    "Наименование (RU)" = "Логическое значение"
    "Тип данных" = "Число"
    "Подтип данных" = "Логический"
    "Точность данных" = 1.0
    "Дробность данных" = 0.0
    "Значение по умолчанию" = 0.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TCODE"
    "Наименование (RU)" = "Мнемокод"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 20.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TCOMPANY"
    "Наименование (RU)" = "Организация"
    "Тип данных" = "Число"
    "Подтип данных" = "Простое число"
    "Точность данных" = 17.0
    "Дробность данных" = 0.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TCRN"
    "Наименование (RU)" = "Каталог"
    "Тип данных" = "Число"
    "Подтип данных" = "Простое число"
    "Точность данных" = 17.0
    "Дробность данных" = 0.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TDATE"
    "Наименование (RU)" = "Дата"
    "Тип данных" = "Дата"
    "Подтип данных" = "Дата (без времени)"
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TIMAGE"
    "Наименование (RU)" = "Изображение"
    "Тип данных" = "Большие двоичные данные"
    "Подтип данных" = "Большие двоичные данные (Изображение)"
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TNAME"
    "Наименование (RU)" = "Наименование"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 160.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TNAMELONG"
    "Наименование (RU)" = "Длинное наименование"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 240.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TNOTEHUGE"
    "Наименование (RU)" = "Очень длинное примечание"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 4000.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TNOTELONG"
    "Наименование (RU)" = "Длинное примечание"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 2000.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TNUMB"
    "Наименование (RU)" = "Номер"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 10.0
    "Выравнивать по длине" = true
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TRESIDENT_SIGN"
    "Наименование (RU)" = "Признак резидентности"
    "Тип данных" = "Число"
    "Подтип данных" = "Простое число"
    "Точность данных" = 1.0
    "Дробность данных" = 0.0
    "Значение по умолчанию" = 2.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = true

        ["Используемые домены"."Домен"."Перечисляемые значения"]

            [["Используемые домены"."Домен"."Перечисляемые значения"."Перечисляемое значение"]]
            "Позиция" = "1"
            "Значение" = 0.0
            "Наименование (RU)" = "Резидент"

            [["Используемые домены"."Домен"."Перечисляемые значения"."Перечисляемое значение"]]
            "Позиция" = "2"
            "Значение" = 1.0
            "Наименование (RU)" = "Нерезидент"

            [["Используемые домены"."Домен"."Перечисляемые значения"."Перечисляемое значение"]]
            "Позиция" = "3"
            "Значение" = 2.0
            "Наименование (RU)" = "Не задан"

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TRN"
    "Наименование (RU)" = "Регистрационный номер"
    "Тип данных" = "Число"
    "Подтип данных" = "Простое число"
    "Точность данных" = 17.0
    "Дробность данных" = 0.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TSEX_TYPE"
    "Наименование (RU)" = "Пол"
    "Тип данных" = "Число"
    "Подтип данных" = "Простое число"
    "Точность данных" = 1.0
    "Дробность данных" = 0.0
    "Значение по умолчанию" = 0.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = true

        ["Используемые домены"."Домен"."Перечисляемые значения"]

            [["Используемые домены"."Домен"."Перечисляемые значения"."Перечисляемое значение"]]
            "Позиция" = "1"
            "Значение" = 0.0
            "Наименование (RU)" = "Не задан"

            [["Используемые домены"."Домен"."Перечисляемые значения"."Перечисляемое значение"]]
            "Позиция" = "2"
            "Значение" = 1.0
            "Наименование (RU)" = "Мужской"

            [["Используемые домены"."Домен"."Перечисляемые значения"."Перечисляемое значение"]]
            "Позиция" = "3"
            "Значение" = 2.0
            "Наименование (RU)" = "Женский"

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TSTR0004"
    "Наименование (RU)" = "Строка 0004"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 4.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TSTR0005"
    "Наименование (RU)" = "Строка 0005"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 5.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TSTR0024"
    "Наименование (RU)" = "Строка 0024"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 24.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TSTR0040"
    "Наименование (RU)" = "Строка 0040"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 40.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TSTR0080"
    "Наименование (RU)" = "Строка 0080"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 80.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TSTR0140"
    "Наименование (RU)" = "Строка 0140"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 140.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "TVERSION"
    "Наименование (RU)" = "Версия"
    "Тип данных" = "Число"
    "Подтип данных" = "Простое число"
    "Точность данных" = 17.0
    "Дробность данных" = 0.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "VARCHAR2(20)"
    "Наименование (RU)" = "VARCHAR2(20)"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 20.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false

    [["Используемые домены"."Домен"]]
    "Мнемокод" = "VARCHAR2(240)"
    "Наименование (RU)" = "VARCHAR2(240)"
    "Тип данных" = "Строка"
    "Подтип данных" = "Простая строка"
    "Размер строки" = 240.0
    "Выравнивать по длине" = false
    "Имеет перечисляемые значения" = false